# Generated by Django 2.1.2 on 2018-10-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='global_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField(max_length=1000)),
                ('fname', models.CharField(max_length=100)),
                ('ftype', models.CharField(max_length=50)),
                ('fpath', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'global_data',
            },
        ),
        migrations.AlterModelTable(
            name='registered_clients',
            table='registered_clients',
        ),
        migrations.AddField(
            model_name='global_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_server.registered_clients'),
        ),
    ]
