# Generated by Django 2.1.2 on 2018-10-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0002_auto_20181008_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_data',
            old_name='user_id',
            new_name='user',
        ),
    ]
