# Generated by Django 2.1.2 on 2018-10-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0003_auto_20181008_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_clients',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registered_clients',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
