# Generated by Django 2.1.2 on 2018-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0005_global_data_md5sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_data',
            name='fdesc',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
