# Generated by Django 2.1.2 on 2018-11-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0006_global_data_fdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_data',
            name='fdesc',
            field=models.CharField(max_length=1000),
        ),
    ]
