# Generated by Django 2.1.2 on 2018-11-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0007_auto_20181121_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_clients',
            name='is_syncing',
            field=models.BooleanField(default=False),
        ),
    ]
